"""add resume file storage columns

Revision ID: 02224d03cb98
Revises: d330f3a84db7
Create Date: 2026-09-04 20:37:53.849167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02224d03cb98'
down_revision: Union[str, Sequence[str], None] = 'd330f3a84db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resume_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_evaluations', schema=None) as batch_op:
        batch_op.drop_column('resume_filename')
        batch_op.drop_column('resume_file_key')

    # ### end Alembic commands ###
