"""add outreach automation followup stage and workspace settings

Revision ID: 1a9c8b70ec0b
Revises: 1168c63db2d6
Create Date: 2026-09-05 21:34:42.198755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9c8b70ec0b'
down_revision: Union[str, Sequence[str], None] = '1168c63db2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('followup_template', sa.String(), nullable=False),
    sa.Column('auto_send_followups', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default so this is safe on a production table that already
    # has rows — every existing entry backfills to 0 ("not an automated
    # follow-up"), which is the correct historical value since this
    # column didn't exist before this batch.
    with op.batch_alter_table('communication_log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followup_stage', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication_log_entries', schema=None) as batch_op:
        batch_op.drop_column('followup_stage')

    op.drop_table('workspace_settings')
    # ### end Alembic commands ###
